version: "3.9"

services:
  db:
    image: postgres:14.2
    restart: always
    ports:
      - "5454:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
  app:
    build: .
    restart: always
    ports:
      - "8081:8080"
    environment:
      - DATASOURCE_HOST=db
      - DATASOURCE_PORT=5432
    depends_on:
      - db
