version: '3.9'

services:
  app:
    build: .
    restart: always
    ports:
      - "8081:8080"
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
      - DATASOURCE_HOST=${DATASOURCE_HOST}
      - DATASOURCE_PORT=${DATASOURCE_PORT}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - MINIO_URL=http://minio:9000
      - MAILHOG_HOST=${MAILHOG_HOST}
      - MAILHOG_PORT=${MAILHOG_PORT}
      - SENTRY_DSN=${SENTRY_DSN}
    depends_on:
      - db
      - minio
      - mailhog
  db:
    image: postgres:14.2
    restart: always
    ports:
      - "5454:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
  minio:
    image: minio/minio
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-storage:/data
  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "1025:1025"
      - "8025:8025"
volumes:
  minio-storage:
