version: "3.9"

services:
  db:
    image: postgres:14.2
    restart: always
    ports:
      - "5454:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
  app:
    build: .
    restart: always
    ports:
      - "8081:8080"
    environment:
      - DATASOURCE_HOST=db
      - DATASOURCE_PORT=5432
      - AWS_S3_ACCESS_KEY_ID=AKIAYBKCLG4M235G4WSV
      - AWS_S3_SECRET_ACCESS_KEY=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
    depends_on:
      - db
